# Generated by Django 5.1.1 on 2025-09-08 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('negative_prompt', models.TextField(blank=True, default='')),
                ('goal', models.CharField(blank=True, max_length=50)),
                ('ad_type', models.CharField(blank=True, max_length=50)),
                ('cta', models.CharField(blank=True, max_length=120)),
                ('slogan', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('size', models.CharField(default='1:1', max_length=10)),
                ('seed', models.BigIntegerField(blank=True, null=True)),
                ('style_preset', models.CharField(blank=True, max_length=50)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('result_url', models.URLField(blank=True)),
                ('thumb_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], default='queued', max_length=12)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
