# Generated by Django 5.1.1 on 2025-09-10 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('refresh_token', models.TextField()),
                ('login_customer_id', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleAdsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=20)),
                ('descriptive_name', models.CharField(blank=True, max_length=255, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='ads.googleadsconnection')),
            ],
            options={
                'unique_together': {('connection', 'customer_id')},
            },
        ),
        migrations.CreateModel(
            name='AdMetricDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=30)),
                ('campaign_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, max_digits=14)),
                ('conversions', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='ads.googleadsaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'date'], name='ads_admetri_account_71970a_idx')],
                'unique_together': {('account', 'campaign_id', 'date')},
            },
        ),
    ]
