# Generated by Django 5.1.1 on 2025-05-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_customerevent_delete_userinteraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(choices=[('view_item', 'View Item'), ('add_to_cart', 'Add to Cart'), ('purchase', 'Purchase')], max_length=50)),
                ('product_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('event_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerEvent',
        ),
    ]
