# Generated by Django 5.1.1 on 2025-05-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_userevent_delete_customerevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='sku',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
