# Generated by Django 5.1.1 on 2025-05-21 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_userevent_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='sku',
        ),
    ]
