# Generated by Django 5.1.1 on 2025-06-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_remove_userevent_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartAbandonment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=100)),
                ('added_at', models.DateTimeField()),
                ('is_purchased', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
