# Generated by Django 5.1.1 on 2025-06-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_cartabandonment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartabandonment',
            name='is_purchased',
        ),
    ]
