# Generated by Django 5.1.1 on 2025-06-07 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_remove_cartabandonment_is_purchased'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartabandonment',
            old_name='email_sent',
            new_name='is_email_sent',
        ),
        migrations.AddField(
            model_name='cartabandonment',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartabandonment',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cartabandonment',
            name='product_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cartabandonment',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
