# Generated by Django 5.1.1 on 2025-07-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='source',
            field=models.CharField(choices=[('organic', 'Organik'), ('mail', 'Mail Kampanyası'), ('ads', 'Reklam'), ('affiliate', 'Affiliate'), ('other', 'Diğer')], default='organic', max_length=50),
        ),
    ]
