# Generated by Django 5.1.1 on 2025-07-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_userevent_utm_campaign_userevent_utm_medium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='source',
        ),
        migrations.AddField(
            model_name='userevent',
            name='utm_content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='utm_term',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='utm_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
