# Generated by Django 5.1.1 on 2025-07-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_remove_userevent_source_userevent_utm_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
