# Generated by Django 5.1.1 on 2025-07-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_userevent_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushSubscription',
        ),
    ]
