# Generated by Django 5.1.1 on 2025-07-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='price_condition',
            field=models.CharField(blank=True, choices=[('higher', 'Daha yüksek'), ('lower', 'Daha düşük')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='price_limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
