# Generated by Django 5.1.1 on 2025-07-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campains', '0002_emailcampaign_price_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
