# Generated by Django 5.1.1 on 2025-07-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campains', '0003_emailcampaign_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='design_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='segment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
