# Generated by Django 5.1.1 on 2025-09-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campains', '0004_emailcampaign_design_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='custom_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='custom_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='subscriber_time_filter',
            field=models.CharField(choices=[('all', 'Tüm Aboneler'), ('1d', 'Son 1 Gün'), ('3d', 'Son 3 Gün'), ('7d', 'Son 7 Gün'), ('30d', 'Son 30 Gün'), ('custom', 'Özel Tarih Aralığı')], default='all', max_length=20),
        ),
    ]
