# Generated by Django 5.1.1 on 2025-05-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinteraction',
            name='interaction_type',
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='event_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
