# Generated by Django 5.1.1 on 2025-05-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_remove_userinteraction_interaction_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInteraction',
        ),
    ]
