# Generated by Django 5.1.1 on 2025-05-21 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_title_product_name_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
