# Generated by Django 5.1.1 on 2025-05-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
