# Generated by Django 5.1.1 on 2025-05-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='embedding',
        ),
    ]
