# Generated by Django 5.1.1 on 2025-06-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_widgetproductselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('hover_image_url', models.URLField(blank=True, null=True)),
                ('price', models.CharField(max_length=50)),
                ('product_url', models.URLField()),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='WidgetProductSelection',
        ),
    ]
