# Generated by Django 5.1.1 on 2025-06-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_widgetproduct_delete_widgetproductselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
